version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  mysql:
    image: mysql:8.0.18
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  gate-simulator:
    build: ./gate-simulator
    container_name: gate-simulator
    ports:
      - '9999:9999'
    volumes:
      - ./gate-simulator:/app
      - /app/node_modules